<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrewerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('breweries')->insert([
            ['user_id' => 991, 'name' => '網走ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '北海道麦酒醸造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ブロイハウス大沼', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '小樽ビール銭函醸造所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '帯広ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'わかさいも本舗', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'オホーツクビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '薄野地麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '大雪地ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'マルカツ興産', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '北海道ワイン', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '耕人舎', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'SOCブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '富良野地麦酒館', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ニセコビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '月と太陽ブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'えぞ麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 1, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '奥入瀬ろまんパーク奥入瀬麦酒館', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 2, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'バイコードリンク', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 2, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'そうま屋米酒店', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 2, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'Be Easy Brewing', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 2, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '銀河高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 3, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '世嬉の一酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 3, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ベアレン醸造所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 3, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '上閉伊酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 3, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '宮城マイクロブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 3, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'あさ開', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 3, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '鳴子温泉ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 4, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '薬莱振興公社', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 4, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '松島ブリューイングカンパニー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 4, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '加工連', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 4, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'あくら', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 5, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'トースト', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 5, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'あきた芸術村', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 5, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '月山ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 6, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '天童果実村ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 6, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '天童ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 6, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '福島路ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 7, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '猪苗代地ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 7, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '木内酒造木内ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 8, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'しもつまブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 8, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '那須高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 9, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'プレストンエール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 9, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '道の駅うつのみや', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 9, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '栃木マイクロブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 9, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '嬬恋高原ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 10, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '龍神酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 10, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '越生ブリュワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'コエドブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '十条すいけんブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '羽生の里', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ぬとりブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'GROW BREW HOUSE', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '川口ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '星野製作所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 11, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ハーヴェストムーン ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 12, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '寒菊銘醸', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 12, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ロコビア', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 12, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ソングバード', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 12, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'こまいぬブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 12, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'アサヒビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '麒麟麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'サントリービール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'サッポロビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '隅田川ブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'T.Y.HARBOR BREWERY', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '石川酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ホッピービバレッジ', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '羽田ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'VERTERE LLC.', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '江戸東京ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '和泉ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '籠屋ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 13, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '足柄地ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '厚木ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'バーバリックワークス）', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '鎌倉ビール醸造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '熊澤酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'クラフトビア・ムーンライト', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '横濱金沢ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '黄金井酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'サンクトガーレン', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '十五麦酒醸造所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '鈴廣', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'たのし屋本舗', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '南横浜ビール研究所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ブリマーブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '横浜ベイブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '横浜ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'T.T BREWERY', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ヨロッコビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '東海道BEER川崎宿工場', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '鍵屋醸造所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'TKBrewing', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 14, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'エチゴビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 15, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'スワンレイクビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 15, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '胎内高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 15, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '八海山泉ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 15, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '新潟麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 15, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '日本海夕陽ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 15, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '宇奈月麦酒館', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 16, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '城端麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 16, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'オオヤブラッスリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 16, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '白山わくわくビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 17, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '越前福井ビール DIOS', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 18, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'アウトサイダー・ブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 19, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '甲斐ドラフトビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 19, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '富士桜高原麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 19, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'Far Yeast Brewing 源流醸造所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 19, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '八ヶ岳ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 19, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'うちゅうブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 19, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'オラホビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 20, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '志賀高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 20, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ヤッホーブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 20, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '軽井沢ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 20, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '塩嶺麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 20, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '南信州ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 20, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '飛騨高山麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 21, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '御殿場高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 22, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ベアードビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 22, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '伊豆高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 22, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '反射炉ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 22, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'バイエルンマイスタービール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 22, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'WEST COAST BREWING', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 22, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '犬山ローラレイ', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 23, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '盛田金しゃちビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 23, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ワイマーケットブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 23, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '伊賀の里モクモク手作りファーム', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 24, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '伊勢角屋麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 24, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '細川酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 24, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '美杉観光開発', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 24, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '長浜浪漫ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 25, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '滋賀酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 25, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '一乗寺ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '黄桜酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'キンシ正宗', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '周山街道ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '京都醸造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '家守堂', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '丹後王国ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 26, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '堺ファーム', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 27, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '箕面ブリュワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 27, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '寿酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 27, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '明石ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 28, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'あわぢびーる工房', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 28, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '小西酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 28, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '曽爾高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 29, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ロート製薬', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 29, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ナギサビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 30, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ボイジャーブルーイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 30, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '和歌山麦酒醸造所三代目', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 30, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '平和酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 30, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'AKARI BREWING', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 31, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'タルマーリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 31, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '倉吉ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 31, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'THINK&CO.', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 31, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '久米桜麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 31, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '島根ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 32, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '石見麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 32, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '三島ファーム', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 32, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '多胡本家酒造場', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '美作ビアワークス', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '宮下酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '吉備土手下麦酒醸造所', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'アクシス', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '三石耐火煉瓦', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'koti brewery', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '吉井高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 33, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '宮島ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 34, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ちょんまげビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 35, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'やまぐち鳴滝高原ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 35, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ライズ&ウィン ブリューイング', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 36, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '香川ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 37, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '梅錦山川', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 38, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '水口酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 38, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '土佐黒潮麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 39, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'オークラブラッスリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 40, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '杉能舎', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 40, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ブルーマスター', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 40, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '門司港地ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 40, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '有田麦酒', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 41, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '阿蘇ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 43, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ゆふいんビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 44, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '雲海酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 45, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '霧島ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 45, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ひでじビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 45, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '霧島高原ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 46, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '薩摩ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 46, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '城山ブルワリー', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 46, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'オリオンビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 47, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => '石垣島ビール', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 47, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
            ['user_id' => 991, 'name' => 'ヘリオス酒造', 'formal_name' => '', 'address' => '', 'access' => '',  'country_id' => 1, 'prefecture_id' => 47, 'created_at' => date('Y-m-t'), 'updated_at' => date('Y-m-t')],
        ]);
    }
}
