<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['country' => '中国'],
            ['country' => 'アメリカ合衆国'],
            ['country' => 'ブラジル'],
            ['country' => 'ドイツ'],
            ['country' => 'メキシコ'],
            ['country' => 'イギリス'],
            ['country' => 'ポーランド'],
            ['country' => 'スペイン'],
            ['country' => '南アフリカ'],
            ['country' => '日本'],
            ['country' => 'ナイジェリア'],
            ['country' => 'ウクライナ'],
            ['country' => 'オランダ'],
            ['country' => 'タイ王国'],
            ['country' => '大韓民国'],
            ['country' => 'ベネズエラ'],
            ['country' => 'コロンビア'],
            ['country' => 'カナダ'],
            ['country' => 'チェコ'],
            ['country' => 'ベルギー'],
            ['country' => 'オーストラリア'],
            ['country' => 'ルーマニア'],
            ['country' => 'アルゼンチン'],
            ['country' => 'フランス'],
            ['country' => 'ペルー'],
            ['country' => 'ベトナム'],
            ['country' => 'イタリア'],
            ['country' => 'アンゴラ'],
            ['country' => 'フィリピン'],
            ['country' => 'トルコ'],
            ['country' => 'オーストリア'],
            ['country' => 'ロシア'],
            ['country' => 'アイルランド'],
            ['country' => 'カメルーン'],
            ['country' => 'ポルトガル'],
            ['country' => 'チリ'],
            ['country' => 'ハンガリー'],
            ['country' => 'デンマーク'],
            ['country' => 'エクアドル'],
            ['country' => 'コンゴ民主共和国'],
            ['country' => 'エチオピア'],
            ['country' => '台湾'],
            ['country' => 'セルビア'],
            ['country' => 'インド'],
            ['country' => 'アゼルバイジャン'],
            ['country' => 'カザフスタン'],
            ['country' => 'ブルガリア'],
            ['country' => 'カンボジア'],
            ['country' => 'スウェーデン'],
            ['country' => 'ドミニカ共和国'],
            ['country' => 'ベラルーシ'],
            ['country' => 'タンザニア'],
            ['country' => 'ケニア'],
            ['country' => 'フィンランド'],
            ['country' => 'ギリシャ'],
            ['country' => 'ボリビア'],
            ['country' => 'ザンビア'],
            ['country' => 'ウガンダ'],
            ['country' => 'スイス'],
            ['country' => 'クロアチア'],
            ['country' => 'コートジボワール'],
            ['country' => 'リトアニア'],
            ['country' => 'コンゴ共和国'],
            ['country' => 'マレーシア'],
            ['country' => 'パナマ'],
            ['country' => 'スロバキア'],
            ['country' => 'ウズベキスタン'],
            ['country' => 'ニュージーランド'],
            ['country' => 'インドネシア'],
            ['country' => 'ガーナ'],
            ['country' => 'キューバ'],
            ['country' => 'ジンバブエ'],
            ['country' => 'ナミビア'],
            ['country' => 'ノルウェー'],
            ['country' => 'ブルンジ'],
            ['country' => 'スロベニア'],
            ['country' => 'グアテマラ'],
            ['country' => 'アルジェリア'],
            ['country' => 'エストニア'],
            ['country' => 'エルサルバドル'],
            ['country' => 'ガボン'],
            ['country' => 'パラグアイ'],
            ['country' => 'ボツワナ'],
            ['country' => 'モザンビーク'],
            ['country' => 'スリランカ'],
            ['country' => 'シンガポール'],
            ['country' => 'ブルキナファソ'],
            ['country' => 'ルワンダ'],
            ['country' => 'マダガスカル'],
            ['country' => 'イスラエル'],
            ['country' => 'チュニジア'],
            ['country' => 'ホンジュラス'],
            ['country' => 'エジプト'],
            ['country' => 'ラトビア'],
            ['country' => 'ウルグアイ'],
            ['country' => 'ジャマイカ'],
            ['country' => 'ベナン'],
            ['country' => 'モルドバ'],
            ['country' => 'モンゴル国'],
            ['country' => 'ボスニア・ヘルツェゴビナ'],
            ['country' => 'ニカラグア'],
            ['country' => 'パプアニューギニア'],
            ['country' => 'チャド'],
            ['country' => 'マケドニア共和国'],
            ['country' => 'スリナム'],
            ['country' => 'ネパール'],
            ['country' => 'アルバニア'],
            ['country' => 'コスタリカ'],
            ['country' => 'トーゴ'],
            ['country' => 'モロッコ'],
            ['country' => 'ラオス'],
            ['country' => 'グルジア'],
            ['country' => 'トリニダード・トバゴ'],
            ['country' => 'キルギス'],
            ['country' => 'モーリシャス'],
            ['country' => '朝鮮民主主義人民共和国'],
            ['country' => 'マラウイ'],
            ['country' => 'キプロス'],
            ['country' => 'レバノン'],
            ['country' => 'ルクセンブルク'],
            ['country' => 'レソト'],
            ['country' => 'ギニア'],
            ['country' => 'アルメニア'],
            ['country' => 'スーダン'],
            ['country' => 'アイスランド'],
            ['country' => 'シエラレオネ'],
            ['country' => '中央アフリカ共和国'],
            ['country' => 'エリトリア'],
            ['country' => 'ガイアナ'],
            ['country' => 'スワジランド'],
            ['country' => 'フィジー	'],
            ['country' => 'セネガル	'],
            ['country' => 'セントルシア'],
            ['country' => 'マリ共和国'],
            ['country' => 'リベリア'],
            ['country' => 'ベリーズ'],
            ['country' => 'マルタ'],
            ['country' => 'シリア'],
            ['country' => 'ヨルダン'],
            ['country' => 'イエメン'],
            ['country' => 'カーボベルデ'],
            ['country' => 'バルバドス'],
            ['country' => 'ニジェール'],
            ['country' => 'ブータン'],
            ['country' => 'サモア'],
            ['country' => 'パキスタン'],
            ['country' => 'セントビンセント・グレナディーン諸島'],
            ['country' => 'セーシェル'],
            ['country' => 'ガンビア'],
            ['country' => 'ソロモン諸島'],
            ['country' => 'モンテネグロ'],
            ['country' => 'グレナダ'],
            ['country' => 'セントクリストファーネイビス'],
            ['country' => 'ギニアビサウ'],
            ['country' => 'タジキスタン'],
            ['country' => 'イラン'],
            ['country' => 'リビア'],
            ['country' => 'アンティグア・バーブーダ'],
            ['country' => 'イラク'],
            ['country' => 'ミャンマー'],
        ]);
    }
}
